version: '3.8'

services:
  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - AIEX_STABLEDIFF_ITERS=40
      - AIEX_ONLINE_TRANSLATION=False
      - AIEX_FILTER_IMAGES=False
      #- AIEX_IMAGE_MODEL=potato
      - AIEX_USE_DATABASE=False
    restart: always
    ports:
      - 8000:8000
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
            
  dalle-frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - dalle-backend
    stdin_open: true
    tty: true

volumes:
  app-cache:
    driver: local
