version: '3'

volumes:
  app-cache:
    driver: local

services:
  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - AIEX_STABLEDIFF_ITERS=40
      - AIEX_ONLINE_TRANSLATION=False
      - AIEX_FILTER_IMAGES=False
    restart: always
    ports:
      - 8000:8000
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
